table _measures
	lineageTag: 6096b91c-6855-4cd7-8d19-89eb00b314d1

	measure 'Total Positive Cases TD' = CALCULATE(SUM(Covid_Cases[positive]), Covid_Cases[date] = MAX(Covid_Cases[date]))
		formatString: #,0
		displayFolder: Positive Cases
		lineageTag: 53d32988-9800-4a5d-a410-68e339b44065

	measure 'Total Death Cases TD' = CALCULATE(SUM(Covid_Cases[death]), Covid_Cases[date] = MAX(Covid_Cases[date]))
		formatString: #,0
		displayFolder: Death Cases
		lineageTag: 5a6db74d-3707-42b0-acbd-0c81f12338cd

	measure 'Total Cases TD' = CALCULATE(SUM(Covid_Cases[total_cases_positive_negative]), Covid_Cases[date] = MAX(Covid_Cases[date]))
		formatString: #,0
		displayFolder: Total Cases
		lineageTag: 457f0dba-0950-4e0b-b3f8-6732c5510ad7

	measure 'Total Recovered Cases TD' = CALCULATE(SUM(Covid_Cases[recovered]), Covid_Cases[date] = MAX(Covid_Cases[date]))
		formatString: #,0
		displayFolder: Recovered Cases
		lineageTag: b23815d5-adb0-4ca7-9868-2bc5fff8edea

	measure 'Increase of positive Cases from Yesterday' = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]), Covid_Cases[date] = MAX(Covid_Cases[date]))
		formatString: #,0
		displayFolder: Positive Cases
		lineageTag: 84dc6e8a-88ff-4dbc-b0c7-54f9ca84f403

	measure Label_Positive_Increase_Decrease_Yesterday = ```
			VAR _positiveincrease = CALCULATE(SUM(Covid_Cases[positive]), Covid_Cases[date] = MAX(Covid_Cases[date]))
			
			                                    RETURN
			                                        SWITCH(TRUE(),
			                                        _positiveincrease > 0, "🔺 from yesterday",
			                                        _positiveincrease < 0, "🔻 from yesterday",
			                                        "🟰 from yesterday"
			                                        )
			                                            
			```
		displayFolder: Positive Cases
		lineageTag: cee5aea1-c4af-4938-9a87-fde7188918c2

	measure '% Positive Cases Increase' = DIVIDE([Increase of positive Cases from Yesterday], [Total Positive Cases TD], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Positive Cases
		lineageTag: 78d12c20-8c51-4b13-bcc9-4462e34088c0

	measure 'Increase of Total Cases yesterday' = ```
			VAR _prevdate = MAX(Covid_Cases[date]) - 1
			                                    VAR _prevtot = CALCULATE(SUM(Covid_Cases[total_cases_positive_negative]), Covid_Cases[date] = _prevdate)
			
			                                    RETURN
			                                        [Total Cases TD] - _prevtot                                   
			```
		formatString: #,0
		displayFolder: Total Cases
		lineageTag: d5e431f8-1f87-4536-b9a5-67338dd3ec3c

	measure Label_Total_Increase_Decrease_Yesterday =
			VAR _prevdate = MAX(Covid_Cases[date]) -1
			                                    VAR _totyesterday = CALCULATE(SUM(Covid_Cases[total_cases_positive_negative]), Covid_Cases[date] = _prevdate)
			
			                                    RETURN
			                                        SWITCH(TRUE(),
			                                        [Total Cases TD] > _totyesterday, "🔺 from yesterday",
			                                        [Total Cases TD] < _totyesterday, "🔻 from yesterday",
			                                        "🟰 from yesterday"
			                                        )
		displayFolder: Total Cases
		lineageTag: 29149d3d-7d5e-4e24-8050-baf1603d975c

	measure '% Total Cases Increase' = DIVIDE([Increase of Total Cases yesterday], [Total Cases TD], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Total Cases
		lineageTag: 25f3e232-4bd2-4fd0-b7a8-3f0577c8836e

	measure Label_Recovered_Increase_Decrease_Yesterday =
			VAR _prevdate = MAX(Covid_Cases[date]) -1
			                                    VAR _totyesterday = CALCULATE(SUM(Covid_Cases[recovered]), Covid_Cases[date] = _prevdate)
			
			                                    RETURN
			                                        SWITCH(TRUE(),
			                                        [Total Recovered Cases TD] > _totyesterday, "🔺 from yesterday",
			                                        [Total Recovered Cases TD] < _totyesterday, "🔻 from yesterday",
			                                        "🟰 from yesterday"
			                                        )
		displayFolder: Recovered Cases
		lineageTag: 6a5c5f4d-5125-4347-bd39-fcc161c230c6

	measure 'Increase of Recovered Cases yesterday' =
			VAR _prevdate = MAX(Covid_Cases[date]) - 1
			                                        VAR _prevtot = CALCULATE(SUM(Covid_Cases[recovered]), Covid_Cases[date] = _prevdate)
			
			                                        RETURN
			                                        [Total Recovered Cases TD] - _prevtot
		formatString: #,0
		displayFolder: Recovered Cases
		lineageTag: e3f8fa1c-57ee-46be-9821-ad417ca23787

	measure '% Recovered Cases Increase' = DIVIDE([Increase of Recovered Cases yesterday], [Total Recovered Cases TD], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Recovered Cases
		lineageTag: 718a0ccc-17f5-44df-b195-9a7fbc39061f

	measure Label_Death_Increase_Decrease_from_Yesterday = ```
			VAR _deathincrease = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]), 
			                                                    Covid_Cases[date] = MAX(Covid_Cases[date]))
			
			                                    RETURN
			                                        SWITCH(TRUE(),
			                                        _deathincrease > 0, "🔺 from yesterday",
			                                        _deathincrease < 0, "🔻 from yesterday",
			                                        "🟰 from yesterday"
			                                        )
			```
		displayFolder: Death Cases
		lineageTag: 48d711a1-3c2d-4697-b533-810366dfb391

	measure 'Increase of Death Cases from Yesterday' =
			CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    Covid_Cases[date] = MAX(Covid_Cases[date]))
		formatString: #,0
		displayFolder: Death Cases
		lineageTag: 911a1c77-9cce-4af1-bc17-33d2c0bff706

	measure '% Death Cases Increase' = DIVIDE([Increase of Death Cases from Yesterday], [Total Death Cases TD], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Death Cases
		lineageTag: 65e1dd18-4a00-40e0-ad16-4a49df27c386

	measure 'Growth Rate Total Cases %' = ```
			/*VAR _maxdate = MAX(DateTable[Date]) 
			                            VAR _month = CALCULATE([Total Cases TD], 
			                                    DateTable[Date] = EOMONTH(_maxdate, -1)
			                                    )
			
			                            VAR _15days = CALCULATE([Total Cases TD],
			                                    DateTable[Date] = _maxdate - 15
			                                    )
			
			                            VAR _week = CALCULATE([Total Cases TD],
			                                    DateTable[Date] = _maxdate - 7
			                                    )
			
			                            RETURN
			                                SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                    "Month",
			                                    DIVIDE([Growth Rate Total Cases], 
			                                            _month, 0),
			                                    "15 Days",
			                                    DIVIDE([Growth Rate Total Cases], 
			                                            _15days, 0),
			                                    "Week",
			                                    DIVIDE([Growth Rate Total Cases], 
			                                            _week, 0)
			                                )*/
			
			                            VAR _dateselected = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                            VAR _total = CALCULATE([Total Cases TD],
			                                                    Covid_Cases[date] =  _dateselected
			                                                )
			
			                            RETURN
			                                --_total
			                                DIVIDE([Growth Rate Total Cases], 
			                                        _total, 
			                                        0
			                                    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Growth Rate\Total Cases
		lineageTag: c5017b9f-b5ba-4b4d-9989-2c318fdf175b

	measure 'Growth Rate Total Cases' = ```
			/*VAR _maxdate = MAX(DateTable[Date]) 
			                            VAR _month = CALCULATE([Total Cases TD], 
			                                    DateTable[Date] = EOMONTH(_maxdate, -1)
			                                    )
			
			                            VAR _15days = CALCULATE([Total Cases TD],
			                                    DateTable[Date] = _maxdate - 15
			                                  )
			
			                            VAR _week = CALCULATE([Total Cases TD],
			                                    DateTable[Date] = _maxdate - 7
			                                    )
			
			                            RETURN
			                                SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                    "Month",
			                                    [Total Cases TD] - _month,
			                                    "15 Days",
			                                    [Total Cases TD] - _15days,
			                                    "Week",
			                                    [Total Cases TD] - _week
			                                )*/
			
			                            VAR _dateselected = MAX(Covid_Cases[date]) - ('Growth Rate Interval'[Growth Rate Interval Value])
			                            VAR _total = CALCULATE([Total Cases TD],
			                                                    Covid_Cases[date] =  _dateselected
			                                                )
			
			                            RETURN
			                                [Total Cases TD] - _total              
			```
		formatString: #,0
		displayFolder: Growth Rate\Total Cases
		lineageTag: c00cf2ca-2aca-4329-8226-59e849237c01

	measure Label_Growth_Rate_Total_Cases = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                                VAR _month = CALCULATE([Total Cases TD], 
			                                                    DateTable[Date] = EOMONTH(_maxdate, -1)
			                                                    )
			
			                                VAR _15days = CALCULATE([Total Cases TD],
			                                        DateTable[Date] = _maxdate - 15
			                                        )
			
			                                VAR _week = CALCULATE([Total Cases TD],
			                                        DateTable[Date] = _maxdate - 7
			                                        )
			
			                                RETURN
			                                    SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                        "Month",
			                                            SWITCH(TRUE(),
			                                                [Total Cases TD] > _month, "🔺 from previous month",
			                                                [Total Cases TD] < _month, "🔻 from previous month",
			                                                "🟰 from previous month"
			                                                    ),
			                                        "15 Days",
			                                            SWITCH(TRUE(),
			                                                [Total Cases TD] > _15days, "🔺 from last 15 Days",
			                                                [Total Cases TD] < _15days, "🔻 from last 15 Days",
			                                                "🟰 from last 15 Days"
			                                                ),
			                                        "Week",
			                                            SWITCH(TRUE(),
			                                                [Total Cases TD] > _week, "🔺 from previous week",
			                                                [Total Cases TD] < _week, "🔻 from previous week",
			                                                "🟰 from previous week"
			                                                )
			                                    )*/
			
			                                    
			                                VAR _selecteddate = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                                VAR _total = CALCULATE([Total Cases TD], 
			                                                    Covid_Cases[date] = _selecteddate
			                                                    )
			
			                                RETURN
			                                SWITCH(TRUE(),
			                                    [Total Cases TD] > _total, "🔺 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                    [Total Cases TD] < _total, "🔻 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                    "🟰 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days"
			                                    )
			                    
			```
		displayFolder: Growth Rate\Total Cases
		lineageTag: 79f48080-fb55-483a-acdc-a939c4b62f04

	measure 'Label Title' = "Covid Cases as of " & FORMAT(MIN(Covid_Cases[date]), "mmm dd, YYYY") & " - " & FORMAT(MAX(Covid_Cases[date]), "mmm dd, YYYY")
		displayFolder: Misc
		lineageTag: 11ee275d-ff25-4b15-9682-2bb0dc9b77f4

	measure 'Growth Rate Positive Cases' = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                VAR _endofmonth = EOMONTH(_maxdate, -1)
			                VAR _startofmonth = DATE(YEAR(_endofmonth), MONTH(_endofmonth), 1)
			                VAR _month = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]), 
			                                    DateTable[Date] >= _startofmonth && 
			                                    DateTable[Date] <= _endofmonth
			                                    )                            
			
			                VAR _startof15 =_maxdate - 14
			                --VAR _startof15 = DATE(YEAR(_endof15), MONTH(_endof15), DAY(_endof15)) 
			                VAR _15days = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                    DateTable[Date] >= _startof15
			                                    --DateTable[Date] <= _maxdatemonth
			                                    )
			
			                VAR _startofweek = _maxdate - 6
			                --VAR _startofweek = DATE(YEAR(_endofweek), MONTH(_endofweek), DAY(_endofweek)) 
			                VAR _week = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                    DateTable[Date] >= _startofweek
			                                    --DateTable[Date] <= _maxdatemonth
			                                    )
			
			                RETURN
			                    SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                        "Month",
			                        _month,
			                        "15 Days",
			                        _15days,
			                        "Week",
			                         _week
			                    )*/
			
			                                VAR _dateselected = MAX(Covid_Cases[date]) - ('Growth Rate Interval'[Growth Rate Interval Value] - 1)
			                                VAR _total = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                        Covid_Cases[date] >= _dateselected
			                                                    )
			
			                                RETURN
			                                    _total      
			```
		formatString: #,0
		displayFolder: Growth Rate\Positive Cases
		lineageTag: 2d54d198-e6a2-4962-9057-35fc6f52d6f0

	measure 'Growth Rate Positive Cases %' = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                                VAR _endofmonth = EOMONTH(_maxdate, -1)
			                                VAR _startofmonth = DATE(YEAR(_endofmonth), MONTH(_endofmonth), 1)
			                                VAR _month = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                       --DateTable[Date] >= _startofmonth &&
			                                                       DateTable[Date] <= _endofmonth
			                                                    )
			
			                                VAR _startof15 = _maxdate - 14
			                                --VAR _startof15 = DATE(YEAR(_endof15), MONTH(_endof15), DAY(_endof15))
			                                VAR _15days = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                        --DateTable[Date] >= _startof15 &&
			                                                        --DateTable[Date] <= _maxdatemonth
			                                                        DateTable[Date] < _startof15
			                                                    )
			
			                                VAR _startofweek = _maxdate - 6
			                                --VAR _startofweek = DATE(YEAR(_endofweek), MONTH(_endofweek), DAY(_endofweek))
			                                VAR _week = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                        --DateTable[Date] >= _startofweek &&
			                                                        --DateTable[Date] <= _maxdatemonth
			                                                        DateTable[Date] < _startofweek
			                                                    )
			
			                                RETURN
			                                    SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                        "Month",
			                                            DIVIDE([Growth Rate Positive Cases],
			                                                    _month, 0),
			                                        "15 Days",
			                                            DIVIDE([Growth Rate Positive Cases],
			                                                    _15days, 0),
			                                        "Week",
			                                            DIVIDE([Growth Rate Positive Cases],
			                                                    _week, 0)
			                                    )*/
			
			                                    VAR _dateselected = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                                    VAR _total = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                            Covid_Cases[date] <=  _dateselected
			                                                        )
			
			                                    RETURN
			                                        DIVIDE([Growth Rate Positive Cases],
			                                                _total,
			                                                0
			                                            )
			                                                        
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Growth Rate\Positive Cases
		lineageTag: 8dd84376-cdeb-441c-bd5e-d40313125196

	measure 'Growth Rate Recovered Cases' =
			/*VAR _maxdate = MAX(DateTable[Date])
			                                VAR _month = CALCULATE([Total Recovered Cases TD],
			                                                     DateTable[Date] = EOMONTH(_maxdate, - 1)
			                                                    )
			
			                                VAR _15days = CALCULATE([Total Recovered Cases TD],
			                                                        DateTable[Date] = _maxdate - 14
			                                                        )
			
			                                VAR _week = CALCULATE([Total Recovered Cases TD],
			                                                        DateTable[Date] = _maxdate - 6
			                                                        )
			
			                                RETURN
			                                    SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                    "Month",
			                                    [Total Recovered Cases TD] - _month,
			                                    "15 Days",
			                                    [Total Recovered Cases TD] - _15days,
			                                    "Week",
			                                    [Total Recovered Cases TD] - _week
			                                    ) */
			
			                                VAR _dateselected = MAX(Covid_Cases[date]) - ('Growth Rate Interval'[Growth Rate Interval Value])
			                                VAR _total = CALCULATE([Total Recovered Cases TD],
			                                                        Covid_Cases[date] = _dateselected
			                                                    )
			
			                                RETURN
			                                    [Total Recovered Cases TD] - _total
		formatString: #,0
		displayFolder: Growth Rate\Recovered Cases
		lineageTag: 5f070c3e-66e2-46b4-b23c-433c4a92bfa2

	measure 'Growth Rate Death Cases' = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                            VAR _endofmonth = EOMONTH(_maxdate, -1)
			                            VAR _startofmonth = DATE(YEAR(_endofmonth), MONTH(_endofmonth), 1)
			                            VAR _month = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                   DateTable[Date] >= _startofmonth &&
			                                                   DateTable[Date] <= _endofmonth
			                                                    )
			
			                            VAR _startof15 = _maxdate - 15
			                            --VAR _startof15 = DATE(YEAR(_endof15), MONTH(_endof15), DAY(_endof15))
			                            VAR _15days = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    DateTable[Date] >= _startof15
			                                                    --DateTable[Date] <= _maxdatemonth                                       
			                                                    )
			
			                            VAR _startofweek = _maxdate - 7
			                            --VAR _startofweek = DATE(YEAR(_endofweek), MONTH(_endofweek), DAY(_endofweek))
			                            VAR _week = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    DateTable[Date] >= _startofweek
			                                                    --DateTable[Date] <= _maxdatemonth
			                                                    )
			
			                            RETURN
			                                SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                    "Month",
			                                        _month,
			                                    "15 Days",
			                                        _15days,
			                                    "Week",
			                                        _week
			                                    )*/
			
			                            VAR _dateseleceted = MAX(Covid_Cases[date]) - ('Growth Rate Interval'[Growth Rate Interval Value] - 1)
			                            VAR _total = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    Covid_Cases[date] >= _dateseleceted
			                                                )
			
			                            RETURN
			                                _total
			```
		formatString: #,0
		displayFolder: Growth Rate\Death Cases
		lineageTag: 883feb9a-836d-4ac1-b7ba-539332445354

	measure Label_Growth_Rate_Positive_Cases = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                                VAR _endofmonth = EOMONTH(_maxdate, -1)
			                                VAR _startofmonth = DATE(YEAR(_endofmonth), MONTH(_endofmonth), 1)
			                                VAR _month = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                       DateTable[Date] >= _startofmonth &&
			                                                       DateTable[Date] <= _endofmonth
			                                                    )
			
			                                VAR _startof15 = _maxdate - 14
			                                --VAR _startof15 = DATE(YEAR(_endof15), MONTH(_endof15), _endof15)
			                                VAR _15days = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                        DateTable[Date] >= _startof15
			                                                        --DateTable[Date] <= _maxdatemonth
			                                                    )
			
			                                VAR _startofweek = _maxdate - 6
			                                --VAR _startofweek = DATE(YEAR(_endofweek), MONTH(_endofweek), _endofweek)
			                                VAR _week = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                        DateTable[Date] >= _startofweek
			                                                        --DateTable[Date] <= _maxdatemonth
			                                                    )
			
			                                RETURN
			                                    SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                        "Month",
			                                            SWITCH(TRUE(),
			                                                [Total Positive Cases TD] > _month, "🔺 from previous month",
			                                                [Total Positive Cases TD] < _month, "🔻 from previous month",
			                                                "🟰 from previous month"
			                                            ),
			                                        "15 Days",
			                                            SWITCH(TRUE(),
			                                                [Total Positive Cases TD] > _15days, "🔺 from previous 15 Days",
			                                                [Total Positive Cases TD] < _15days, "🔻 from previous 15 Days",
			                                                "🟰 from previous month"
			                                            ),
			                                        "Week",
			                                            SWITCH(TRUE(),
			                                                [Total Positive Cases TD] > _week, "🔺 from previous week",
			                                                [Total Positive Cases TD] < _week, "🔻 from previous week",
			                                                "🟰 from previous month"
			                                            )
			                                    )*/
			
			                                    VAR _dateselected = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                                    VAR _total = CALCULATE(SUM(Covid_Cases[positive_increase_from_previous_day]),
			                                                            Covid_Cases[date] < _dateselected
			                                                        )
			
			                                    RETURN
			                                        SWITCH(TRUE(),
			                                            [Total Positive Cases TD] > _total, "🔺 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                            [Total Positive Cases TD] < _total, "🔻 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                            "🟰 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days"
			                                            )
			                                        
			```
		displayFolder: Growth Rate\Positive Cases
		lineageTag: 25fe79fd-a65a-4295-ba19-6b776419e77e

	measure 'Growth Rate Recovered Cases %' = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                                VAR _month = CALCULATE([Total Recovered Cases TD],
			                                                        DateTable[Date] = EOMONTH(_maxdate, -1)
			                                                    )
			
			                                VAR _15days = CALCULATE([Total Recovered Cases TD],
			                                                        DateTable[Date] = _maxdate - 15
			                                                    )
			
			                                VAR _week = CALCULATE([Total Recovered Cases TD],
			                                                        DateTable[Date] = _maxdate - 7
			                                                    )
			
			                                RETURN
			                                    SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                        "Month",
			                                            DIVIDE([Total Recovered Cases TD] - _month,
			                                                    _month, 0),
			                                        "15 Days",
			                                            DIVIDE([Total Recovered Cases TD] - _15days,
			                                                    _15days, 0),
			                                        "week",
			                                            DIVIDE([Total Recovered Cases TD] - _week,
			                                                    _week, 0 )
			                                        )*/
			
			                                VAR _dateselected = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                                VAR _total = CALCULATE([Total Recovered Cases TD],
			                                                        Covid_Cases[date] = _dateselected
			                                                    )
			
			                                RETURN
			                                    DIVIDE([Growth Rate Recovered Cases],
			                                            _total,
			                                            0
			                                        )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Growth Rate\Recovered Cases
		lineageTag: bcae7b25-7112-4572-bc1e-accd66daa3a6

	measure Label_Growth_Rate_Recovered_Cases = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                                VAR _month = CALCULATE([Total Recovered Cases TD],
			                                                        DateTable[Date] = EOMONTH(_maxdate, -1)
			                                                    )
			
			                                VAR _15days = CALCULATE([Total Recovered Cases TD],
			                                                        DateTable[Date] = _maxdate - 15
			                                                    )
			
			                                VAR _week = CALCULATE([Total Recovered Cases TD],
			                                                         DateTable[Date] = _maxdate - 7
			                                                    )
			
			                                RETURN
			                                    SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                        "Month",
			                                            SWITCH(TRUE(),
			                                                [Total Recovered Cases TD] > _month, "🔺 from previous month",
			                                                [Total Recovered Cases TD] < _month, "🔻 from previous month",
			                                                "🟰 from previous month"
			                                                    ),
			                                        "15 Days",
			                                            SWITCH(TRUE(),
			                                                [Total Recovered Cases TD] > _15days, "🔺 from last 15 Days",
			                                                [Total Recovered Cases TD] < _15days, "🔻 from last 15 Days",
			                                                "🟰 from last 15 Days"
			                                                ),
			                                        "Week",
			                                            SWITCH(TRUE(),
			                                                [Total Recovered Cases TD] > _week, "🔺 from previous week",
			                                                [Total Recovered Cases TD] < _week, "🔻 from previous week",
			                                                "🟰 from previous week"
			                                                )
			                                    )    */
			
			                                VAR _dateselected = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                                VAR _total = CALCULATE([Total Recovered Cases TD],
			                                                        Covid_Cases[date] = _dateselected
			                                                    )
			                                        
			                                RETURN
			                                    SWITCH(TRUE(),
			                                        [Total Recovered Cases TD] > _total, "🔺 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                        [Total Recovered Cases TD] < _total, "🔻 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                        "🟰 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days"
			                                        )
			```
		displayFolder: Growth Rate\Recovered Cases
		lineageTag: 4522a5f2-fe56-4bcb-aa76-8320e1ad58bb

	measure 'Growth Rate Death Cases %' = ```
			/*VAR _maxdate = MAX(DateTable[Date])
			                            VAR _endofmonth = EOMONTH(_maxdate, -1)
			                            VAR _startofmonth = DATE(YEAR(_endofmonth), MONTH(_endofmonth), 1)
			                            VAR _month = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    --DateTable[Date] >= _startofmonth && 
			                                                    DateTable[Date] <= _endofmonth
			                                                )
			
			                            VAR _startof15 = _maxdate - 14
			                            VAR _15days = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                     DateTable[Date] >= _startof15 
			                                                )
			
			                            VAR _startofweek = _maxdate - 6
			                            VAR _week = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    DateTable[Date] >= _startofweek
			                                                )
			
			                            RETURN
			                                SWITCH(SELECTEDVALUE('Growth Rate'[Interval]),
			                                    "Month",
			                                        )*/
			
			                            VAR _dateselected = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                            VAR _total = CALCULATE(sum(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    Covid_Cases[date] <= _dateselected
			                                                )
			
			                            RETURN
			                                DIVIDE([Growth Rate Death Cases],
			                                        _total,
			                                        0
			                                    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Growth Rate\Death Cases
		lineageTag: 2432d348-d687-43c4-b39b-b975bbe70040

	measure Label_Growth_Rate_Death_Case =
			VAR _dateselected = MAX(Covid_Cases[date]) - 'Growth Rate Interval'[Growth Rate Interval Value]
			                            VAR _total = CALCULATE(SUM(Covid_Cases[death_increase_calculated_from_current day - previous day]),
			                                                    Covid_Cases[date] > _dateselected
			                                                )
			
			                            RETURN
			                                SWITCH(TRUE(),
			                                        [Total Death Cases TD] > _total, "🔺 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                        [Total Death Cases TD] < _total, "🔻 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days",
			                                        "🟰 from the last " & 'Growth Rate Interval'[Growth Rate Interval Value] & " days"
			                                    )
		displayFolder: Growth Rate\Death Cases
		lineageTag: 7d3706d3-fb3b-48e8-a0be-88d800592333

	measure 'Total Cases & Forecast' = ```
			
			VAR _getlatestnoofcases = CALCULATE([Total Cases TD], 
			                                    ALLSELECTED(Covid_Cases), 
			                                    Covid_Cases[date] = MAXX(ALL(Covid_Cases), 
			                                                        Covid_Cases[date]
			                                                        )
			                                )
			
			-- Get the last 3 months of ACTUAL data and Average
			VAR _previoussales = CALCULATE([Total Cases TD],
			                                DateTable[Date] = EOMONTH(MAX(DateTable[Date]),-1)
			                            )
			
			VAR _avg3months= CALCULATE([Total Cases 3-Month Avg],
			                                DateTable[Date] = EOMONTH(MAX(DateTable[Date]),-1)
			                            )
			
			VAR _sumavgsales = _avg3months + _previoussales
			
			RETURN
			    IF(NOT ISBLANK([Total Cases TD]),
			        [Total Cases TD],
			        _getlatestnoofcases + _avg3months)
			                            
			```
		displayFolder: Forecast
		lineageTag: 09287e0b-e4f4-4ca1-8377-c22455b1672a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cases 3-Month Avg' = ```
			VAR _prevmonth = CALCULATE([Total Cases TD],
			                                                        ALLSELECTED(Covid_Cases), 
			                                                        DateTable[Date] = EOMONTH(MAX(DateTable[Date]), -3)
			                                                    )
			
			                            VAR _curmonth = CALCULATE([Total Cases TD],
			                                                        ALLSELECTED(Covid_Cases), 
			                                                        DateTable[Date] = MAX(DateTable[Date])
			                                                    )
			
			                            RETURN
			                                IF(NOT ISBLANK([Total Cases TD]),   
			                                    DIVIDE(_curmonth - _prevmonth,
			                                            3
			                                        )
			                                )
			
			
			```
		displayFolder: Forecast
		lineageTag: 867e54db-ffc0-4dc3-ba79-2476a2c5e46b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Forecast (Dynamic Stepwise 3-Month)' = ```
			
			VAR _lastActualDate =
			    CALCULATE(
			        MAX(Covid_Cases[date]),
			        REMOVEFILTERS(Covid_Cases)
			    )
			
			VAR _forecastDate = MAX(DateTable[Date])
			
			-- Determine how many months ahead the current date is
			VAR _monthsAhead =
			    DATEDIFF(
			        _lastActualDate,
			        _forecastdate,
			        MONTH
			    )      
			
			-- Get the value of last 3 month
			VAR _prev3months = CALCULATE([Total Cases TD],
			                            ALLSELECTED(Covid_Cases), 
			                            DateTable[Date] = EOMONTH(MAX(DateTable[Date]), 
			                                                    -4
			                                                    )
			                            )
			
			VAR _prev4months = CALCULATE([Total Cases TD],
			                            ALLSELECTED(Covid_Cases), 
			                            DateTable[Date] = EOMONTH(MAX(DateTable[Date]), 
			                                                    -5
			                                                    )
			                            )
			--for the first forecast
			VAR _previouscases = CALCULATE([Total Cases TD],
			                                DateTable[Date] = EOMONTH(MAX(DateTable[Date]),-(_monthsAhead))
			                            )
			
			VAR _avg3months= CALCULATE([Total Cases 3-Month Avg],
			                            DateTable[Date] = EOMONTH(MAX(DateTable[Date]),-(_monthsAhead))
			                        )
			
			VAR _sumavgcases = _avg3months + _previouscases
			
			-- Recursive-style loop simulation
			-- If 1 month ahead → use base forecast
			-- If >1 → use rolling average of previous 3 (mix of actual + forecast)
			VAR _forecast =
			    SWITCH(
			        TRUE(),
			        _monthsAhead = 1, _sumavgcases,
			
			        _monthsAhead = 2,
			            --For the second forecast
			            VAR _tot3monthdiff = DIVIDE(_sumavgcases - _prev3months,
			                                        3
			                                        )
			            VAR _2sumavgcases = _sumavgcases + _tot3monthdiff
			            RETURN
			                _2sumavgcases,
			                
			        _monthsAhead = 3,
			            --For the third forecast
			            VAR _tot4monthdiff = DIVIDE(_sumavgcases - _prev4months,
			                                        3
			                                        )
			            VAR _copy2sumavgcases = _sumavgcases +  _tot4monthdiff
			            VAR _totcases = DIVIDE(_copy2sumavgcases - _prev3months,
			                                    3
			                                )
			            VAR _3sumavgcases = _totcases + _copy2sumavgcases
			            RETURN
			                _3sumavgcases,
			                
			        [Total Cases TD]
			        )
			
			    
			
			RETURN
			--IF(_isFutureMonth, _forecast)
			_forecast
			```
		displayFolder: Forecast
		lineageTag: c24dcb4e-684b-4eb7-80da-f3fc5d7a4fdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cases Group by Date' = ```
			
			VAR _mindate = CALCULATE(MIN(DateTable[Date]), 
			                        ALLSELECTED(DateTable)
			                        )
			
			VAR _lastActualDate =
			    CALCULATE(
			        MAX(Covid_Cases[date]),
			        REMOVEFILTERS(Covid_Cases)
			            )
			
			VAR _forecastDate = MAX(DateTable[Date])
			
			VAR _prevmonth = CALCULATE([Total Cases TD],
			                            ALLSELECTED(Covid_Cases), 
			                            DateTable[Date] = EOMONTH(MAX(DateTable[Date]), -1)
			                        )
			
			VAR _curmonth = CALCULATE([Total Cases TD],
			                            ALLSELECTED(Covid_Cases), 
			                            DateTable[Date] = MAX(DateTable[Date])
			                        )
			
			VAR _monthsAhead = DATEDIFF(_lastActualDate,
			                            _forecastDate,
			                            MONTH
			                        )
			
			
			
			VAR _totalcases =
			    SWITCH(TRUE(),
			        _monthsAhead = 1,"",
			
			        _monthsAhead = 2, "",
			
			        _monthsAhead = 3, "",
			        
			        IF(NOT ISBLANK([Total Cases TD]) && _mindate <> MIN(DateTable[Date]),   
			            _curmonth - _prevmonth
			            )
			        )
			
			RETURN
			    _totalcases    
			
			```
		displayFolder: Forecast
		lineageTag: 27fabac6-2988-4e99-bca6-baf77279066b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Date Difference' =
			
			/*VAR _forecastdate =
			    CALCULATE(MAX(DateTable[Date]), REMOVEFILTERS(DateTable))
			
			VAR _lastActualDate = MAX(DateTable[Date])
			*/
			VAR _lastActualDate =
			    CALCULATE(
			        MAX(Covid_Cases[date]),
			        REMOVEFILTERS(Covid_Cases)
			    )
			
			VAR _currentDate = MAX(DateTable[Date])
			
			-- Determine how many months ahead the current date is
			VAR _monthsAhead =
			    DATEDIFF(
			        EOMONTH(_lastActualDate, 0),
			        EOMONTH(_currentDate, 0),
			        MONTH
			    )
			
			RETURN
			_monthsAhead
		formatString: 0
		displayFolder: Forecast
		lineageTag: d975d4b6-7905-4400-b1cd-4e189d637515

	measure 'Forecast Group by Date(Dynamic Stepwise 3-Month)' = ```
			
			VAR _lastActualDate =
			    CALCULATE(
			        MAX(Covid_Cases[date]),
			        REMOVEFILTERS(Covid_Cases)
			    )
			
			VAR _forecastDate = MAX(DateTable[Date])
			
			-- Determine how many months ahead the current date is
			VAR _monthsAhead =
			    DATEDIFF(
			        _lastActualDate,
			        _forecastdate,
			        MONTH
			    )      
			
			-- Get the value of last 3 month
			VAR _prev3months = CALCULATE([Total Cases TD],
			                            ALLSELECTED(Covid_Cases), 
			                            DateTable[Date] = EOMONTH(MAX(DateTable[Date]), 
			                                                    -4
			                                                    )
			                            )
			
			VAR _prev4months = CALCULATE([Total Cases TD],
			                            ALLSELECTED(Covid_Cases), 
			                            DateTable[Date] = EOMONTH(MAX(DateTable[Date]), 
			                                                    -5
			                                                    )
			                            )
			--for the first forecast
			VAR _previouscases = CALCULATE([Total Cases TD],
			                                DateTable[Date] = EOMONTH(MAX(DateTable[Date]),-(_monthsAhead))
			                            )
			
			VAR _avg3months= CALCULATE([Total Cases 3-Month Avg],
			                            DateTable[Date] = EOMONTH(MAX(DateTable[Date]),-(_monthsAhead))
			                        )
			
			VAR _sumavgcases = _avg3months + _previouscases
			
			-- Recursive-style loop simulation
			-- If 1 month ahead → use base forecast
			-- If >1 → use rolling average of previous 3 (mix of actual + forecast)
			VAR _forecast =
			    SWITCH(
			        TRUE(),
			        _monthsAhead = 1, _avg3months,
			
			        _monthsAhead = 2,
			            --For the second forecast
			            VAR _tot3monthdiff = DIVIDE(_sumavgcases - _prev3months,
			                                        3
			                                        )
			            RETURN
			                _tot3monthdiff,
			                
			        _monthsAhead = 3,
			            --For the third forecast
			            VAR _tot4monthdiff = DIVIDE(_sumavgcases - _prev4months,
			                                        3
			                                        )
			            VAR _copy2sumavgcases = _sumavgcases +  _tot4monthdiff
			            VAR _totcases = DIVIDE(_copy2sumavgcases - _prev3months,
			                        3
			                    )
			            RETURN
			                _totcases,
			                
			        [Total Cases Group by Date]
			        )
			
			    
			
			RETURN
			--IF(_isFutureMonth, _forecast)
			_forecast
			```
		formatString: #,0
		displayFolder: Forecast
		lineageTag: 34f3c518-342a-4098-862c-8cfaa1ceb761

	partition _measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

