table 'Growth Rate'
	lineageTag: ce796539-0c2d-4410-a57e-8a2eb7954268

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 28a97a30-6f8a-47d2-a009-c17acf37a25c
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Interval
		dataType: string
		lineageTag: 597ca0be-6456-4cc1-ae38-62cb3f6902e5
		summarizeBy: none
		sourceColumn: Interval
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Growth Rate' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfLNzyvJUIrViVYyAvIMTRVcEiuLwXxjID88NTVbKTYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Index = _t, Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Index", Int64.Type}, {"Column1", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Interval"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

